# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET http://localhost:5264/Movies

###
GET http://localhost:5264/Movies/7


###
GET http://localhost:5264/Movies/4
###
POST http://localhost:5264/Movies
Content-Type: application/json

{
  "title": "12 Angry Men",
  "GenreId": 2,
  "director": "Sidney Lumet",
  "ticketPrice": 44.5,
  "releaseDate": "1957-04-10"
}

###
Put http://localhost:5264/Movies/7
Content-Type: application/json

{
  "title": "12 Angry Men",
  "GenreId": 2,
  "director": "Sidney Lumet",
  "ticketPrice": 24.5,
  "releaseDate": "1957-04-10"
}

###
DELETE http://localhost:5264/Movies/1