# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET http://localhost:5264/Movies

###
GET http://localhost:5264/Movies/1


###
GET http://localhost:5264/Movies/4
###
POST http://localhost:5264/Movies
Content-Type: application/json

{
  "title": "12 Angry Men",
  "genre": "Crime",
  "director": "Sidney Lumet",
  "ticketPrice": 1114.5,
  "releaseDate": "1957-04-10"
}

###
Put http://localhost:5264/Movies/1
Content-Type: application/json

{
  "title": "12 Angry Men",
  "genre": "Crime",
  "director": "Sidney Lumet",
  "ticketPrice": 11214.5,
  "releaseDate": "1957-04-10"
}

###
Delete http://localhost:5264/Movies/1